# Generated by Django 3.2 on 2022-02-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220114_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_weight',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='isfavourite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
