# Generated by Django 3.2 on 2022-02-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220207_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isfavourite',
        ),
    ]
