# Generated by Django 3.2 on 2022-02-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-date_added']},
        ),
    ]
