# Generated by Django 3.2 on 2022-04-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_favouriteslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_favourite',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
